# Generated by Django 4.2.4 on 2023-08-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_Creacion_de_tablas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamodel',
            name='nivel_azucar',
            field=models.TextField(choices=[['MUY_ALTO', 'MUY_ALTO'], ['ALTO', 'ALTO'], ['MEDIO', 'MEDIO'], ['BAJO', 'BAJO'], ['MUY_BAJO', 'MUY_BAJO'], ['CERO', 'CERO']], db_column='nivel_azucar'),
        ),
        migrations.RenameField(
            model_name='categoriamodel',
            old_name='nivel_azucar',
            new_name='nivelAzucar',
        ),
        migrations.AlterField(
            model_name='golosinamodel',
            name='fecha_vencimiento',
            field=models.DateField(db_column='fecha_vencimiento', editable=False),
        ),
        migrations.RenameField(
            model_name='golosinamodel',
            old_name='fecha_vencimiento',
            new_name='fechaVencimiento',
        ),
        migrations.AlterUniqueTogether(
            name='golosinamodel',
            unique_together={('nombre', 'fechaVencimiento')},
        ),
    ]
