"""elimine columna direccion

Revision ID: 6a441144a085
Revises: ebee5edfffaa
Create Date: 2023-07-26 22:43:36.246331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a441144a085'
down_revision = 'ebee5edfffaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
